#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#define BUTTON_UP SDLK_u
#define BUTTON_DOWN SDLK_d
#define BUTTON_LEFT SDLK_l
#define BUTTON_RIGHT SDLK_r
#define BUTTON_A SDLK_a
#define BUTTON_B SDLK_b
#define BUTTON_MENU SDLK_q
#define BUTTON_VOLDOWN SDLK_m
#define BUTTON_VOLUP SDLK_n
#define BUTTON_SOUNDSWITCH SDLK_y
#define BUTTON_GLOWSWITCH SDLK_x
#define BUTTON_DARKSWITCH SDLK_s

#define DEFAULT_WINDOW_WIDTH 240
#define DEFAULT_WINDOW_HEIGHT 240

#endif